on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'
      - '.github/workflows/infrastructure.yml'

concurrency:
  group: deploy-infrastructure
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Get secrets from Secret Manager
        run: |
          echo "TF_VAR_github_token=$(gcloud secrets versions access latest --secret=github-token)" >> $GITHUB_ENV
          echo "TF_VAR_tailscale_api_key=$(gcloud secrets versions access latest --secret=tailscale-api-key)" >> $GITHUB_ENV
          echo "TF_VAR_tailscale_auth_key=$(gcloud secrets versions access latest --secret=tailscale-auth-key)" >> $GITHUB_ENV

      - name: Set up Nix
        uses: ./.github/actions/install-nix

      - name: Tofu Init
        run: nix develop .#infrastructure --command tofu init
        working-directory: infrastructure

      - name: Tofu fmt
        run: nix develop .#infrastructure --command tofu fmt -check
        working-directory: infrastructure

      - name: Tofu validate
        run: nix develop .#infrastructure --command tofu validate
        working-directory: infrastructure

      - name: Tofu Plan
        run: nix develop .#infrastructure --command tofu plan
        working-directory: infrastructure

      - name: Tofu Apply
        run: nix develop .#infrastructure --command tofu apply -auto-approve
        working-directory: infrastructure