on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'
      - '.github/workflows/terraform-tofu.yml'

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Nix
        uses: ./.github/actions/install-nix

      - name: Tofu Init
        run: nix develop --command tofu init
        working-directory: infrastructure
        env:
          TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Tofu Plan
        run: nix develop --command tofu plan
        working-directory: infrastructure
        env:
          TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Tofu Apply
        run: nix develop --command tofu apply -auto-approve
        working-directory: infrastructure
        env:
          TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
